### ISSUE TITLE
featurerequest: String parsing

### ISSUE THREAD

**Issue by nsharmon** [nicolewhite/algebra.js#7] opened 2015-08-17 09:11 UTC
It would be very elegant to be able to write:

```javascript
var expr = new Expression("2x + 3");
```

In the place of:

```javascript
var expr = new Expression("x");
expr = expr.subtract(3);
expr = expr.add("x");
```

This would of course require a parser which is not going to be light, so it could possibly be an optional require should Expression find a non-variable string passed.  I would keep it internal though.  If anything parsing information can be made available later.  

With your approval, I'll try to get a very simple parser working.  The real trick will be to get operations to be performed in the proper order.  I'll probably end up using a regular expression to check if the expression is a variable, and, afterwards prior to parsing, potentially valid before beginning to parse.

If done properly, the parser would perform the equivalent of the latter code when presented with the string "2x + 3".

**Comment by timrach** [comment] 2015-08-17 15:09
I actually did this. It is very small (lexer ~100 lines, parser ~200lines) but it seems to work. 
Here: https://github.com/timrach/algebra-parser
Demo: http://timrach.github.io/algebra-parser/

**Comment by nicolewhite** [comment] 2015-08-17 16:17
Yes, this is the same request as https://github.com/nicolewhite/algebra.js/issues/5. Of course I approve of this addition. I think it (the Parse class) can be maintained internally, and when initializing an Expression you check if it's a variable string or expression string. If it's [A-z] or one of the Greek letters, then it's just a variable; otherwise, parse the expression.

@timrach that's very cool, I love the demo. Would you be willing to contribute the code to this lib directly?

**Comment by timrach** [comment] 2015-08-17 22:38
@nicolewhite Sure! I'll fork the repo and just add the parser module to the algebra.js module exports. That way the existing code stays the way it is. Is that okay?

**Comment by nicolewhite** [comment] 2015-08-17 22:46
I'd rather do what @nsharmon suggested and keep the Parser and Lexer classes internal. It can always be exposed later, if necessary.

**Comment by timrach** [comment] 2015-08-18 00:04
The problem is, that the parser returns an equation if it reads an equation and returns an expression if it reads an expression, because that's what the grammar tells it. 
So for an input like this:
```
	var expr = new Expression('x^2 + 4 = 20');
```
the parser would need the information that it is supposed to parse an expression and
throw an error when it reads the '='. 
Same scenario applies for an equation where the '=' is missing.  
Besides, to support automatic parsing as suggested, it would be necessary to construct
wrapper classes for the Expression and Equation classes because the Parser is using those classes
internally to construct the result.  
The point is: code quality and maintenance will decrease significantly if the parser 
is integrated in the existing classes and if you want to keep the existing functionality.
If the Parser module is exposed seperately, not a single line of existing code in 
the other modules needs to be touched. The Lexer module can be kept internal of course.

Both solutions are possible and will work, but i really recommend keeping the parser on a higher level than the expression and equation classes to keep things simple and readable.

**Comment by kevinb7** [comment] 2015-08-18 00:33
Maybe the `parse` method could be exposed on the main `algebra` object, e.g.
```
let algebra = require("algebra");
let eqn = alegbra.parse("12x + 5 = 7");
```

**Comment by nicolewhite** [comment] 2015-08-18 02:38
Okay @timrach, I see your point. I like @kevinb7's suggestion of putting the `parse` method on the `algebra` object. What do you think?

**Comment by ivanistheone** [comment] 2015-08-18 04:32
+1 for @kevinb7's suggestion of making reading strings a top-level function:

    algebra = require("algebra");
    
    // define equation
    var eqn = alegbra.parse("12x + 5 = 7");

    // define expr
    var expr = alegbra.parse("12x + 5")

Yeah it's a bit weird that parse can return either an Equation or an Expression, but hey this is js, who is gonna stop us?

RE name of function --- parse seems too computer-jargony, `read`?, `create`?   Actually, come to think of it `parse` is probably the best ;)

**Comment by ivanistheone** [comment] 2015-08-18 05:48
Another js mathy parser for possible code reuse or inspiration: https://github.com/Khan/KAS/blob/master/kas.js#L79 via [Jison](http://zaach.github.io/jison/demos/calc/) with tests: https://github.com/Khan/KAS/blob/master/test.html#L55

**Comment by nsharmon** [comment] 2015-08-18 06:10
Yeah, I realized that I couldn't internalize it because Expression would
need to know about the parser and vice versa.  I have a very basic parser
up and working.  Still working on the kinks, but I'll do a pull request if
you like.  If anything, perhaps we can get the best of both worlds?

Also, I decided that x2 would be variable with name x2 and 2x is 2*x.  Let
me know if that's fine.  That also means that xy is a single variable by
this system, so you'd have to explicitly write x*y.

**Comment by timrach** [comment] 2015-08-18 08:00
@nicolewhite @kevinb7's suggestion is perfect. I'll do that.

**Comment by nicolewhite** [comment] 2015-08-19 16:15
I'll close this once it gets added to the docs page at http://algebra.js.org. I'm going to throw this into a 0.2.0 release along with the changes I'm adding over on the [simplify](https://github.com/nicolewhite/algebra.js/tree/simplify) branch.

**Comment by nicolewhite** [comment] 2015-08-21 06:26
Closing this now that it's added to the docs. Any bugs with the parser should be created as separate issues.

**Closed by nicolewhite** 2015-08-21 06:26 UTC
Labels: enhancement
